// ============================================================
// Event cover art — the LOCKED IP illustration contract.
// Art is generated server-side (generate-event-image) and stored on
// events.image_url. This section is the visual acceptance reference.
// ============================================================
import { SectionWrapper, SubSection } from "../components/SectionWrapper";

interface Props {
  isMobile: boolean;
}

const SAMPLES: Array<{ id: string; title: string; prop: string; accent: string }> = [
  {
    id: "f1-drivers-2026",
    title: "Who wins the 2026 F1 drivers' championship?",
    prop: "wearing a racing suit and lifting a golden championship trophy",
    accent: "Volt Green",
  },
  {
    id: "us-coin-updown-20260731",
    title: "Coinbase (COIN) — will close higher today?",
    prop: "holding a COIN ticker board, one paw on chin, thinking",
    accent: "Volt Green",
  },
];

const RULES: Array<[string, string]> = [
  ["Ground", "Flat warm paper grey #F2F2F0 with subtle grain. No gradient, no scene, no vignette."],
  ["Character", "The one lynx IP: thick black ink line, charcoal fur, tan #B49A6A markings, white whiskers, half-lidded skeptical face, chibi 1.5a : a proportions."],
  ["Accent", "Exactly ONE brand accent per image — Pulse Blue #33D6FF by default, Volt Green #CFFF4A only for bullish / winning semantics. Props may keep one essential local colour (trophy gold)."],
  ["Prop", "Driven by the event title: stock → ticker board + thinking pose; sports → kit / trophy; macro → the symbol. One prop only."],
  ["Frame", "Single character centred, full body, generous margins, square 1:1."],
  ["Never", "Headline text, logos, UI frames, borders, watermarks, humans, rainbow palettes, drop shadows on the ground. Short ticker labels printed on a prop are the only allowed lettering."],
];

export const EventArtSection = ({ isMobile }: Props) => (
  <SectionWrapper id="event-art" title="Event cover art (LOCKED)" platform="shared">
    <SubSection title="Contract">
      <div className="overflow-hidden rounded-xl border border-border/40">
        {RULES.map(([k, v]) => (
          <div
            key={k}
            className="flex flex-col gap-0.5 border-b border-border/30 px-3 py-2 last:border-b-0 sm:flex-row sm:gap-4"
          >
            <span className="w-24 shrink-0 font-mono text-[10px] uppercase tracking-[0.16em] text-muted-foreground">
              {k}
            </span>
            <span className="text-xs text-foreground/90">{v}</span>
          </div>
        ))}
      </div>
      <p className="mt-2 text-xs text-muted-foreground">
        Generated by the <span className="font-mono">generate-event-image</span> backend function on
        listing; the result is written to <span className="font-mono">events.image_url</span>. If
        generation fails the card falls back to the category image — never a broken tile.
      </p>
    </SubSection>

    <SubSection title="Approved samples">
      <div className={isMobile ? "grid grid-cols-2 gap-3" : "grid grid-cols-4 gap-4"}>
        {SAMPLES.map((s) => (
          <figure key={s.id} className="space-y-1.5">
            <div className="aspect-square overflow-hidden rounded-xl border border-border/40 bg-[#F2F2F0]">
              <img
                src={`/event-art-samples/${s.id}.png`}
                alt={s.title}
                loading="lazy"
                className="h-full w-full object-cover"
              />
            </div>
            <figcaption className="space-y-0.5">
              <p className="text-[11px] font-semibold leading-tight text-foreground">{s.title}</p>
              <p className="text-[10px] text-muted-foreground">{s.prop}</p>
              <p className="font-mono text-[10px] text-muted-foreground/80">accent: {s.accent}</p>
            </figcaption>
          </figure>
        ))}
      </div>
    </SubSection>
  </SectionWrapper>
);